name: architectural_base
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_ioc: ^2.1.0
  flutter_ioc_get_it: ^1.2.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
